spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.h2.Driver
    username: ${USER_NAME}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace
